# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Repository\ConnA\TableRepository:
        class: App\Repository\ConnA\TableRepository
        public: false
        arguments:
            $entityManager: '@doctrine.orm.my_aaa_connection_entity_manager'

    App\Repository\ConnZ\LampRepository:
        class: App\Repository\ConnZ\LampRepository
        public: false
        arguments:
            $entityManager: '@doctrine.orm.my_zzz_connection_entity_manager'

    App\EventSubscriber\TableSubscriber:
        tags:
            -
                name: doctrine.event_subscriber
                connection: my_aaa_connection
